language: go

go:
  - 1.5
  - tip

install:
  - go get -t -d -v ./...
  - go get github.com/onsi/ginkgo/ginkgo
  - go get -u github.com/golang/lint/golint

services:
  - mongodb
# make mongodb a replica set
before_script:
  - echo "replSet = testRs" | sudo tee -a /etc/mongodb.conf
  - sudo service mongodb restart
  - sleep 20
  - mongo --eval 'rs.initiate()'
  - sleep 15

script: 
  - TEST_CONFIGURATION=travis-configuration.json ginkgo -r --randomizeAllSpecs --randomizeSuites --failOnPending --trace --race --progress
