language: go

go:
  - 1.5
  - tip

before_install:
  - sudo apt-get -qq update
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10 
  - echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/mongodb.list
  - sudo apt-get update
  - sudo apt-get install -y mongodb-org
  - ulimit -a
  - ulimit -c unlimited || true 
  - make clean testenv

install:
  - go get -t -d -v ./...
  - go get github.com/onsi/ginkgo/ginkgo
  - go get -u github.com/golang/lint/golint
  - go get -u github.com/modocache/gover
  - go get -u github.com/mattn/goveralls

before_script:
  - mongo --eval 'tojson(db.runCommand({buildInfo:1}))'
  - sleep 15

script: 
  - ginkgo -r -cover --randomizeSuites --failOnPending --trace --race --progress
  - gover
  - goveralls -coverprofile=gover.coverprofile -repotoken pHTNrf97AGyJ56AkQmnPisOvlnaS1rlBo

notifications:
  email: false
